modules/agent/controllers/DouyinCommentController.php
<?php

namespace app\modules\agent\controllers;

use app\modules\agent\AdminController;
use Yii;
use app\models\DouyinComment;
use app\models\search\DouyinCommentSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\View;

/**
 * DouyinCommentController implements the CRUD actions for DouyinComment model.
 */
class DouyinCommentController extends AdminController
{
    /**
     * Lists all DouyinComment models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DouyinCommentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single DouyinComment model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new DouyinComment model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new DouyinComment();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing DouyinComment model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing DouyinComment model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the DouyinComment model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return DouyinComment the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = DouyinComment::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/agent/controllers/DouyinItemController.php
<?php

namespace app\modules\agent\controllers;

use app\models\DouyinAccount;
use app\models\search\DouyinAccountSearch;
use app\models\Video;
use app\modules\agent\AdminController;
use Yii;
use app\models\DouyinItem;
use app\models\search\DouyinItemSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * DouyinItemController implements the CRUD actions for DouyinItem model.
 */
class DouyinItemController extends AdminController
{
    /**
     * Lists all DouyinItem models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DouyinItemSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $douyin_account_ids = DouyinAccount::find()->select('id')->where(['wx_uid'=>Yii::$app->user->id])->column();
        $dataProvider->query->andWhere(['douyin_account_id'=>$douyin_account_ids]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single DouyinItem model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
    public function actionShow($id)
    {
        $obj = DouyinItem::findOne($id);
        $arr = json_decode($obj->item_data,1);
        return $this->redirect($arr['share_url']);
    }

    /**
     * Creates a new DouyinItem model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($video_id)
    {
        $video = Video::findOne($video_id);
        if(empty($video)){
            throw new \Exception('参数错误',1);
        }
        if(Yii::$app->user->id != $video->wx_uid){
            throw new \Exception('无权限',1);
        }
        $searchModel = new DouyinAccountSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('create', [
            'video' => $video,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
   }

    /**
     * Updates an existing DouyinItem model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing DouyinItem model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the DouyinItem model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return DouyinItem the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = DouyinItem::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/agent/views/douyin-item/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\DouyinItem */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="douyin-item-form">

    <?php $form = ActiveForm::begin(); ?>


    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>


    <?= $form->field($model, 'cover')->fileInput(['multiple'=>false,'accept'=>'*',]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/agent/views/douyin-item/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\DouyinItemSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="douyin-item-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'type') ?>

    <?= $form->field($model, 'item_id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'cover') ?>

    <?php // echo $form->field($model, 'is_top') ?>

    <?php // echo $form->field($model, 'comment_count') ?>

    <?php // echo $form->field($model, 'digg_count') ?>

    <?php // echo $form->field($model, 'download_count') ?>

    <?php // echo $form->field($model, 'play_count') ?>

    <?php // echo $form->field($model, 'share_count') ?>

    <?php // echo $form->field($model, 'forward_count') ?>

    <?php // echo $form->field($model, 'item_data') ?>

    <?php // echo $form->field($model, 'item_state') ?>

    <?php // echo $form->field($model, 'create_time') ?>

    <?php // echo $form->field($model, 'post_time') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/agent/views/douyin-item/create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\DouyinItem */

$this->title = '发布';
$this->params['breadcrumbs'][] = ['label' => '发布管理', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$this->registerJsFile('//gosspublic.alicdn.com/aliyun-oss-sdk-6.8.0.min.js',['position'=>\yii\web\View::POS_BEGIN]);

?>
<div class="douyin-item-create">
    <table class="table table-striped table-bordered">
        <tbody>
        <tr>
            <td><?=$video->title?></td>
            <td><?=$video->showSize()?></td>
            <td><?=$video->showDuration()?></td>
        </tr>
        </tbody>
    </table>
</div>

<div class="douyin-account-index">
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= \yii\grid\GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'label'=>'选择',
                'filter'=>false,
                'format'=>'raw',
                'value'=>function($model)use($video){
                    return Html::checkbox('account_ids',false,['onchange'=>'choose(this,'.$video->id.','.$model->id.')']);
                }
            ],
            [
                'label'=>'发布账号ID',
                'attribute'=>'id',
            ],
            [
                'label'=>'发布账号头像',
                'attribute'=>'avatar',
                'filter'=>false,
                'format'=>'raw',
                'value'=>function($model){
                    return '<img src="'.$model->avatar.'"/>';
                }
            ],
//            'douyin_app_id',
            [
                'label'=>'发布账号昵称',
                'attribute'=>'nickname',
            ],
            //'avatar',
            //'douyin_uid',
            //'access_token',
            [
                'label'=>'发布标题',
                'filter'=>false,
                'format'=>'raw',
                'value'=>function($model)use($video){
                    return Html::textarea('title',$video->title,['rows'=>5,'cols'=>30]);
                }
            ],
        ],
    ]); ?>


</div>
<div class="form-group">
    <?= Html::submitButton('发布', ['onclick'=>'publish()','class' => 'btn btn-success']) ?>
</div>
<script>
    let account_arr = new Array();
    function choose(obj,video_id,account_id) {
        if(obj.checked){
            let title = $(obj).parent().parent().find('*[name="title"]').first();
            account_arr[account_id] = {"video_id":video_id,"account_id":account_id,"title":title.val()};
        }else{
            delete(account_arr[account_id]);
        }
        console.log(account_arr);
        //account_arr[account_id] =
    }
    function publish() {
        if(confirm("后台运行,需要几分钟时间")){
            $.ajax({
                contentType: 'application/json',
                type: 'POST',
                url:'/agent/ajax/publish',
                data:JSON.stringify(account_arr),
                success:function (res) {
                    console.log(res)
                }
            });

        }
    }
</script>

modules/agent/views/douyin-item/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\DouyinItemSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = '抖音发布';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="douyin-item-index">
    <p>
        <?= Html::a('发布', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
                'id',
            [
                'attribute'=>'douyin_account_id',
                'filter'=>false,
//                'format'=>'raw',
                'value'=>function($model){
                    return $model->douyinAccount->nickname;
                }
            ],
            [
                'attribute'=>'账号头像',
                'filter'=>false,
                'format'=>'raw',
                'value'=>function($model){
                    return '<img width="60" src="'.$model->douyinAccount->avatar.'"/>';
                }
            ],
//            'type',
            'title',
            [
                'attribute'=>'cover',
                'filter'=>false,
                'format'=>'raw',
                'value'=>function($model){
                    return '<a target="_blank" href="/agent/douyin-item/show?id='.$model->id.'"><img width="60" src="'.$model->cover.'"/></a>';
                }
            ],
            //'is_top',
            [

                'attribute'=>'comment_count',
//                'filter'=>false,
                'format'=>'raw',
                'value'=>function($model){
                    return Html::a($model->comment_count, ['douyin-comment/index','DouyinCommentSearch[item_id]'=>$model->id]);
                }
            ],
            'digg_count',
            'download_count',
            'play_count',
            'share_count',
            'forward_count',
            //'item_data:ntext',
            //'item_state',
            [

                'attribute'=>'create_time',
                'filter'=>false,
//                'format'=>'raw',
                'value'=>function($model){
                    return date('Y-m-d H:i:s',$model->create_time);
                }
            ],
            'create_time:datetime:ymdH',
            'post_time:date:ymdhis',
            [
                'label'=>'操作',
                'filter'=>false,
                'format'=>'raw',
                'value'=>function($model){
                    return Html::a('更新详情', '#here', ['class' => 'btn btn-success','onclick'=>'syncItem('.$model->id.')']).
                        '<br/>'.Html::a('更新评论', '#here', ['class' => 'btn btn-success','onclick'=>'syncComment('.$model->id.')']).
                        '<br/>'.Html::a('删除', '#here', ['class' => 'btn btn-danger','onclick'=>'del('.$model->id.')']);
                }
            ],
        ],
    ]); ?>


</div>
<script>
    function syncItem(id){
        if(confirm('确定要实时更新此视频信息吗')){
            $.post('/agent/ajax/sync-item',{id:id},function (req) {
                checkresult(req);
            });
        }
    }
    function syncComment(id){
        if(confirm('后台运行，可能需要几分钟时间')){
            $.post('/agent/ajax/sync-comment',{id:id},function (req) {
                checkresult(req);
            });
        }
    }
    function del(id){
        alert('暂时未开放此权限');
        return;
        if(confirm('确定删除吗？删除后不可恢复')){
            $.post('/agent/ajax/del-item',{id:id},function (req) {
                checkresult(req);
            });
        }
    }
</script>

modules/agent/views/douyin-item/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\DouyinItem */

$this->title = 'Update Douyin Item: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Douyin Items', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="douyin-item-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/agent/views/douyin-item/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\DouyinItem */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Douyin Items', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="douyin-item-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'type',
            'item_id',
            'title',
            'cover',
            'is_top',
            'comment_count',
            'digg_count',
            'download_count',
            'play_count',
            'share_count',
            'forward_count',
            'item_data:ntext',
            'item_state',
            'create_time:datetime',
            'post_time:datetime',
        ],
    ]) ?>

</div>