modules/agent/controllers/AuthCommentController.php
<?php

namespace app\modules\agent\controllers;

use app\models\AuthAccount;
use app\models\DouyinEmoji;
use app\modules\agent\AdminController;
use Yii;
use app\models\AuthComment;
use app\models\search\AuthCommentSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AuthCommentController implements the CRUD actions for AuthComment model.
 */
class AuthCommentController extends AdminController
{
    /**
     * Lists all AuthComment models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AuthCommentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $auth_account_ids = AuthAccount::find()->select('id')->where(['uid'=>Yii::$app->user->id])->column();
        $dataProvider->query->andWhere(['auth_account_id'=>$auth_account_ids]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'emojis' => DouyinEmoji::getEmojiHtml(),
        ]);
    }

    /**
     * Displays a single AuthComment model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new AuthComment model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new AuthComment();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing AuthComment model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing AuthComment model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the AuthComment model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return AuthComment the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = AuthComment::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/agent/controllers/AuthItemController.php
<?php

namespace app\modules\agent\controllers;

use app\models\AuthAccount;
use app\models\search\AuthAccountSearch;
use app\models\Video;
use app\modules\agent\AdminController;
use Yii;
use app\models\AuthItem;
use app\models\search\AuthItemSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AuthItemController implements the CRUD actions for AuthItem model.
 */
class AuthItemController extends AdminController
{
    //显示视频
    public function actionShow($id)
    {
        $obj = AuthItem::findOne($id);
        return $this->redirect($obj['show_url']);
    }
    /**
     * Lists all AuthItem models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AuthItemSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $auth_account_ids = AuthAccount::find()->select('id')->where(['uid'=>Yii::$app->user->id])->column();
        $dataProvider->query->andWhere(['auth_account_id'=>$auth_account_ids]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCreate($video_id)
    {
        $video = Video::findOne($video_id);
        if(empty($video)){
            throw new \Exception('参数错误',1);
        }
        if(Yii::$app->user->id != $video->wx_uid){
            throw new \Exception('无权限',1);
        }
        $searchModel = new AuthAccountSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['uid'=>Yii::$app->user->id]);

        return $this->render('create', [
            'video' => $video,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Updates an existing AuthItem model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing AuthItem model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the AuthItem model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return AuthItem the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = AuthItem::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/agent/views/auth-item/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\AuthItem */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="auth-item-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'auth_app_id')->textInput() ?>

    <?= $form->field($model, 'auth_account_id')->textInput() ?>

    <?= $form->field($model, 'video_id')->textInput() ?>

    <?= $form->field($model, 'item_id')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'cover')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'is_top')->textInput() ?>

    <?= $form->field($model, 'comment_count')->textInput() ?>

    <?= $form->field($model, 'digg_count')->textInput() ?>

    <?= $form->field($model, 'download_count')->textInput() ?>

    <?= $form->field($model, 'play_count')->textInput() ?>

    <?= $form->field($model, 'share_count')->textInput() ?>

    <?= $form->field($model, 'forward_count')->textInput() ?>

    <?= $form->field($model, 'timing')->textInput() ?>

    <?= $form->field($model, 'post_time')->textInput() ?>

    <?= $form->field($model, 'create_time')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/agent/views/auth-item/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\AuthItemSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="auth-item-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'auth_app_id') ?>

    <?= $form->field($model, 'auth_account_id') ?>

    <?= $form->field($model, 'video_id') ?>

    <?= $form->field($model, 'item_id') ?>

    <?php // echo $form->field($model, 'title') ?>

    <?php // echo $form->field($model, 'cover') ?>

    <?php // echo $form->field($model, 'is_top') ?>

    <?php // echo $form->field($model, 'comment_count') ?>

    <?php // echo $form->field($model, 'digg_count') ?>

    <?php // echo $form->field($model, 'download_count') ?>

    <?php // echo $form->field($model, 'play_count') ?>

    <?php // echo $form->field($model, 'share_count') ?>

    <?php // echo $form->field($model, 'forward_count') ?>

    <?php // echo $form->field($model, 'timing') ?>

    <?php // echo $form->field($model, 'post_time') ?>

    <?php // echo $form->field($model, 'create_time') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/agent/views/auth-item/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\AuthItem */

$this->title = '发布';
$this->params['breadcrumbs'][] = ['label' => '发布管理', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="douyin-item-create">
    <table class="table table-striped table-bordered">
        <tbody>
        <tr>
            <td><?=$video->title?></td>
            <td><?=$video->showSize()?></td>
            <td><?=$video->showDuration()?></td>
        </tr>
        </tbody>
    </table>
</div>

<div class="douyin-account-index">
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= \yii\grid\GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'label'=>'选择',
                'filter'=>false,
                'format'=>'raw',
                'value'=>function($model)use($video){
                    return Html::checkbox('account_ids',false,['value'=>$model->id]);
                }
            ],
//            [
//                'label'=>'发布账号ID',
//                'attribute'=>'id',
//            ],
            [
                'label'=>'发布账号头像',
                'attribute'=>'avatar',
                'options'=>['wdith'=>'100px'],
                'filter'=>false,
                'format'=>'raw',
                'value'=>function($model){
                    return $model->authUser->showAvatar();
                    return '<img src="'.$model->avatar.'"/>';
                }
            ],
//            'douyin_app_id',
            [
                'label'=>'发布账号昵称',
                'attribute'=>'nickname',
            ],
            //'avatar',
            //'douyin_uid',
            //'access_token',
            [
                'label'=>'发布标题',
                'filter'=>false,
                'format'=>'raw',
                'value'=>function($model)use($video){
                    return Html::textarea('titles',$video->title,['rows'=>5,'cols'=>30]).Html::hiddenInput('auth_app_ids',$model->auth_app_id);
                }
            ],
            [
                'label'=>'发布时间',
                'filter'=>false,
                'format'=>'raw',
                'value'=>function($model){
                    return Html::radioList('timings['.$model->id.']',2,\app\models\AuthItem::$timing_arr).Html::input('datetime-local','post_times');
                }
            ],
        ],
    ]); ?>


</div>
<div class="form-group">
    <?= Html::submitButton('提交', ['onclick'=>'publish()','class' => 'btn btn-success']) ?>
</div>
<script>
    let video_id = <?=$video->id?>;
    function publish() {
        let data_arr = new Array();
        $('input[name="account_ids"]:checked').each(function () {
            let auth_account_id = $(this).val();
            let auth_app_id = $(this).parent().parent().find('*[name="auth_app_ids"]').first().val();
            let title = $(this).parent().parent().find('*[name="titles"]').first().val();
            let timing = $(this).parent().parent().find('*[name^="timings"]:checked').val();
            let post_time = $(this).parent().parent().find('*[name="post_times"]').first().val();
            console.log(auth_account_id);
            data_arr.push({video_id:video_id,auth_account_id:auth_account_id,auth_app_id:auth_app_id,title:title,timing:timing,post_time:post_time});
        });
        if(data_arr.length <1){
            alert('请选择');
            return ;
        }
        // console.log(data_arr);
        // return ;
        if(confirm("后台运行,需要几分钟时间,视频越大需要的时间越长")){
            $.ajax({
                contentType: 'application/json',
                type: 'POST',
                url:'/agent/ajax/publish',
                data:JSON.stringify(data_arr),
                success:function (res) {
                    console.log(res)
                    window.location.href = '/agent/auth-item';
                }
            });
        }
    }
</script>

modules/agent/views/auth-item/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\AuthItemSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = '发布管理';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="auth-item-index">
    <p>
        <?= Html::a('发布', ['/agent/video'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'id',
            [
                'attribute'=>'auth_account_id',
                'filter'=>false,
//                'format'=>'raw',
                'value'=>function($model){
                    return $model->authAccount->nickname;
                }
            ],
            [
                'attribute'=>'账号头像',
                'filter'=>false,
                'format'=>'raw',
                'value'=>function($model){
                    return '<img width="60" src="'.$model->authAccount->avatar.'"/>';
                }
            ],
//            'type',
            'title',
            [
                'attribute'=>'cover',
                'filter'=>false,
                'format'=>'raw',
                'value'=>function($model){
                    return '<a target="_blank" href="/agent/auth-item/show?id='.$model->id.'">'.$model->showCover().'</a>';
                }
            ],
            //'is_top',
            [

                'attribute'=>'comment_count',
//                'filter'=>false,
                'format'=>'raw',
                'value'=>function($model){
//                    return Html::a($model->comment_count, ['auth-comment/index','AuthCommentSearch[item_id]'=>$model->id]);
                    return $model->comment_count;
                }
            ],
            'digg_count',
            'play_count',
            [
                'label'=>'分享/转发/下载',
                'filter'=>false,
                'format'=>'raw',
                'value'=>function($model){
                    return $model->share_count.'/'.$model->forward_count.'/'.$model->download_count;
                }
            ],

            //'item_data:ntext',
            //'item_state',
            [

                'attribute'=>'create_time',
                'filter'=>false,
//                'format'=>'raw',
                'value'=>function($model){
                    return date('Y-m-d H:i',$model->create_time);
                }
            ],
            [
                'attribute'=>'timing',
                'filter'=>false,
//                'format'=>'raw',
                'value'=>function($model){
                    return $model->showTiming();
                }
            ],
            [
                'attribute'=>'post_time',
                'filter'=>false,
//                'format'=>'raw',
                'value'=>function($model){
                    return date('Y-m-d H:i',$model->post_time);
                }
            ],
            [
                'attribute'=>'state',
                'filter'=>false,
//                'format'=>'raw',
                'value'=>function($model){
                    return $model->showState();
                }
            ],
            [
                'label'=>'操作',
                'filter'=>false,
                'format'=>'raw',
                'value'=>function($model){
                    $str = Html::a('更新详情', '#here', ['class' => 'btn btn-success','onclick'=>'syncItem('.$model->id.')']);
                    $str .= '<br/>'.Html::a('更新评论', '#here', ['class' => 'btn btn-success','onclick'=>'syncComment('.$model->id.')']);
//                    $str .= '<br/>'.Html::a('删除', '#here', ['class' => 'btn btn-danger','onclick'=>'del('.$model->id.')']);
                    return $str;
                }
            ],
        ],
    ]); ?>


</div>
<script>
    function syncItem(id){
        if(confirm('确定要实时更新此视频信息吗')){
            $.post('/agent/ajax/sync-item',{id:id},function (req) {
                checkresult(req);
            });
        }
    }
    function syncComment(id){
        if(confirm('后台运行，可能需要几分钟时间')){
            $.post('/agent/ajax/sync-comment',{id:id},function (req) {
                checkresult(req);
            });
        }
    }
    function del(id){
        alert('暂时未开放此权限');
        return;
        if(confirm('确定删除吗？删除后不可恢复')){
            $.post('/agent/ajax/del-item',{id:id},function (req) {
                checkresult(req);
            });
        }
    }
</script>

modules/agent/views/auth-item/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\AuthItem */

$this->title = 'Update Auth Item: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Auth Items', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="auth-item-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/agent/views/auth-item/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\AuthItem */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Auth Items', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="auth-item-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'auth_app_id',
            'auth_account_id',
            'video_id',
            'item_id',
            'title',
            'cover',
            'is_top',
            'comment_count',
            'digg_count',
            'download_count',
            'play_count',
            'share_count',
            'forward_count',
            'timing',
            'post_time:datetime',
            'create_time:datetime',
        ],
    ]) ?>

</div>